services:

  web:
    build: .
    container_name: trafficcrash-web
    restart: unless-stopped

    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - ./php_file:/var/www/html

    ports:
      - "8081:80"

    depends_on:
      - mysql
  mysql:
    image: mysql:8.4
    container_name: trafficcrash-db
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: trafficcrash
      MYSQL_USER: trafficuser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - trafficcrash_mysql_data:/var/lib/mysql

    ports:
      - "3306:3306"

volumes:
  trafficcrash_mysql_data: